services:
  auth:
    image: dino147/auth:latest
    ports:
      - "5001:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:my-secret-pw@postgres:5432/auth-db"
  games:
    image: dino147/games:latest
    ports:
      - "5002:8000"
    depends_on:
      - postgres2
  reviews:
    image: dino147/reviews:latest
    ports:
      - "5003:8000"
    depends_on:
      - postgres3
  library:
    image: dino147/library:latest
    ports:
      - "5004:8000"
    depends_on:
      - postgres4
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: auth-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth-db"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  postgres2:
    image: postgres:latest
    container_name: postgres-2
    environment:
      POSTGRES_PASSWORD: game-pw
      POSTGRES_DB: game-db
    volumes:
      - postgres2_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d game-db"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  postgres3:
    image: postgres:latest
    container_name: postgres-3
    environment:
      POSTGRES_PASSWORD: reviews-pw
      POSTGRES_DB: reviews-db
    volumes:
      - postgres3_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reviews-db"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
      
  postgres4:
    image: postgres:latest
    container_name: postgres-4
    environment:
      POSTGRES_PASSWORD: library-pw
      POSTGRES_DB: library-db
    volumes:
      - postgres4_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library-db"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  frontend:
    image: dino147/frontend:latest
    environment:
      AUTH_URL: "http://auth:8000"
      GAMES_URL: "http://games:8000"
      REVIEWS_URL: "http://reviews:8000"
      LIBRARY_URL: "http://library:8000"
    ports:
      - "5000:8000"
volumes:
  postgres_data:
  postgres2_data:
  postgres3_data:
  postgres4_data:
